### ISSUE TITLE
Mods required

### ISSUE THREAD

**Issue by chrisinthailand** [TaskForceAthena/TFA-Modlists#1]
The mod list should include WW2 Objects which is required for IFA-Lite and several TFA Factions for Campaigns in progress
https://steamcommunity.com/sharedfiles/filedetails/?id=937438041&searchtext=ww2+objects

**Comment by sasshunter** [comment]
This (i.e. Modern Univeral) mod list is for modern missions - historical campaigns may use their own list if it is not covered by it (i.e. pre-90's or so)

**Comment by chrisinthailand** [comment]
Roger, leaves me in a quandary for the spare time campaign I've been working on which is based on The Man In The High Castle, and requires WW2 German Uniforms but modern weapons and equipment, If I continue to develop it will have to add the WW2 Mod as a campaign only requirement
