### ISSUE TITLE
1 "FIREWILL Aviation Pack" mod insted of the 3 "usaf" mods

### ISSUE THREAD

**Issue by MishaMishaMiiiii** [TaskForceAthena/TFA-Modlists#4]
1. the lower number of mods the better.

2. Pilot only needs zeus to spawn the plane and 1 rearm container, as the pilot can rearm, refuel, repair and change the pylons and there weapons.

3. A f*ck ton of planes and variants of that plane.
01) @A-10 Warthog
02) @AV-8b Harrier 2 +GR ver
03) @EA-18G Growler
04) @F-2 Viper ZERO
05) @F-14 Tomcat
06) @F-15 Eagle
07) @F-16 Fighting Falcon
08) @F-22 Raptor
09) @FIR AWS(AirWeaponSystem)
10) @F-23 Grey Ghost
11) @F/A-181E Black Wasp II
12) @ SU-25SM3 Grach
13) @Ace combat 7 Reskin pack
14) @MQ-81 Harpy
15) @Project Rhino Demo
16) @Project Lightning - F-35B Armaverse Version
17) @F-A-18 Hornet
18) @FIR Veterans request skin pack
19) @ Project Tornado

4.New weapons: https://docs.google.com/document/d/1v73_wgL0llB09QiIX3BCOKMBdBltnY6fYWPwHio_87c/edit

mod link: https://steamcommunity.com/sharedfiles/filedetails/?id=1381545544

**Comment by mollybeam** [comment]
1. Plainly false
2. Pilots can do this with other aircraft through ACE as well

Per the process, this is being presented to officers

**Comment by mollybeam** [comment]
Officers agreed that there was no need for a large fast air pack
