### ISSUE TITLE
Australia

### ISSUE THREAD

**Issue by MishaMishaMiiiii** [TaskForceAthena/TFA-Modlists#5]
https://steamcommunity.com/sharedfiles/filedetails/?id=1381545544
A realy big 40km by 40km map has enterable buildings, big sitys, desert, flats, forests and more. We can use it alot before we do missions every where on it

**Comment by mollybeam** [comment]
You've linked to firewill's complete pack again, please correct.

**Comment by MishaMishaMiiiii** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=485417177&searchtext=australia
